CAMPAIGN_MAP_WIDTH = 1600
CAMPAIGN_MAP_HEIGHT = 900

CAMPAIGN_HOME_BASE_POSITION = (180, 720)

DEFAULT_CAMPAIGN_MAX_SPAWNS = 18
DEFAULT_CAMPAIGN_SPAWN_INTERVAL = 10.0
DEFAULT_CAMPAIGN_INITIAL_SPAWN_DELAY = 2.0

DEFAULT_RETURN_TIME_MULTIPLIER = 1.0
DEFAULT_REST_TIME = 14.0

HERO_STATE_AVAILABLE = "available"
HERO_STATE_TRAVELING = "traveling"
HERO_STATE_ON_TASK = "on_task"
HERO_STATE_AWAITING_DECISION = "awaiting_decision"
HERO_STATE_RETURNING = "returning"
HERO_STATE_RESTING = "resting"

TASK_STATE_PENDING = "pending"
TASK_STATE_TRAVELING_TO = "traveling_to"
TASK_STATE_ACTIVE = "active"
TASK_STATE_WAITING_FOR_DECISION = "waiting_for_decision"
TASK_STATE_AWAITING_ACK = "awaiting_ack"
TASK_STATE_RETURNING = "returning"
TASK_STATE_COMPLETED = "completed"
TASK_STATE_FAILED = "failed"
TASK_STATE_EXPIRED = "expired"